USE mysql;
CREATE USER 'root'@'%' IDENTIFIED WITH auth_socket BY 'Root!123';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
CREATE USER 'hahlabs'@'%' IDENTIFIED BY 'Hahlabs!123';
GRANT ALL PRIVILEGES ON *.* TO 'hahlabs'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

