FROM node:latest as build
RUN npm install -g @angular/cli
# Set the working directory
WORKDIR /usr/apps

# Add the source code to app
RUN ng new ng-app
WORKDIR /usr/apps/ng-app
# Install all the dependencies
COPY ./app.component.html src/app
RUN npm install

# Serve the application
EXPOSE 4200
CMD ng serve --host 0.0.0.0 

# docker build -f Dockerfile-angular -t hahlabs/angular:init .
# docker run -dp 4200:4200 --name angular-app hahlabs/angular:init 
