FROM hahlabs/angular:init as build
WORKDIR /usr/apps/ng-app
RUN npm install
RUN npm run build
# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest

# Copy the build output to replace the default nginx contents.
COPY --from=build /usr/apps/ng-app/dist/ng-app /usr/share/nginx/html

EXPOSE 80
EXPOSE 4200

# docker build -f Dockerfile-nginx-angular -t hahlabs/nginx-angular:init .
# docker run -dp 80:80 --name nginx-angular-app hahlabs/nginx-angular:init 

